" == Install vim-plug == {{{1
let s:settings_plug_path = expand('~/.vim/autoload/plug.vim')
if !filereadable(s:settings_plug_path)
  silent! exec 'silent !curl -fkLo "' . s:settings_plug_path . '" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  silent! exec 'source ' . s:settings_plug_path
endif


" == Plugins == {{{1
call plug#begin('~/.vim/plugged')
" Theme
Plug 'gruvbox-community/gruvbox'
" Plug 'joshdick/onedark.vim'
Plug 'rakr/vim-one'
" Plug 'nanotech/jellybeans.vim'
" Plug 'dracula/vim', { 'as': 'dracula' }

" Rainbow Parentheses
Plug 'junegunn/rainbow_parentheses.vim'

" Show Hex Colors
if executable("go")
  Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase','on': ['HexokinaseToggle']}
  let g:Hexokinase_highlighters = ['background']
endif

" Hightligh Yank
Plug 'machakann/vim-highlightedyank'
  let g:highlightedyank_highlight_duration = 100

" Underlines the word under the cursor
" Plug 'itchyny/vim-cursorword'

" Marks
Plug 'kshenoy/vim-signature'

" Indent Line
Plug 'Yggdroot/indentLine', { 'on': 'IndentLinesEnable' }

" Edit
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-abolish'
Plug 'andrewradev/splitjoin.vim'
" Plug 'bronson/vim-trailing-whitespace', { 'on': 'FixWhitespace' }
" Plug 'junegunn/vim-easy-align'
" Plug 'AndrewRadev/switch.vim'
" Plug 'mg979/vim-visual-multi', {'branch': 'master'}

" Move
" Extended "%" matching
Plug 'benjifisher/matchit.zip'

Plug 'easymotion/vim-easymotion'
" Plug 'unblevable/quick-scope'

" text object
" Plug 'kana/vim-textobj-user'
" Plug 'kana/vim-textobj-line'
" Plug 'kana/vim-textobj-entire'
" Plug 'kana/vim-textobj-indent'

" Search
Plug 'junegunn/fzf',        { 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" Handle multi-file find and replace.
" Plug 'mhinz/vim-grepper'

" Plug 'dyng/ctrlsf.vim'
" Plug 'ctrlpvim/ctrlp.vim'
" Plug 'mileszs/ack.vim'

" Tag
Plug 'majutsushi/tagbar', { 'on': 'TagbarToggle' }
" Plug 'ludovicchabant/vim-gutentags'

" netrw
Plug 'tpope/vim-vinegar'
" netrw
"   let g:netrw_banner = 1
"   let g:netrw_browse_split = 4
"   let g:netrw_altv = 1
  let g:netrw_liststyle = 3
"   let g:netrw_winsize = 25
map <C-n> :Vexplore<CR>

" Tree explorer
" Plug 'vim-scripts/vtreeexplorer'
" let treeExplVertical = 1
" let treeExplWinSize = 30
" let treeExplHidden = 1

" UndoTree
Plug 'mbbill/undotree', { 'on': 'UndotreeToggle' }

" Choose Windows
" Plug 't9md/vim-choosewin'
" nmap <C-w><C-w> <Plug>(choosewin)

" Git
" Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-fugitive'
" Git commit browser. Requires fugitive.
Plug 'junegunn/gv.vim'

" Shows a git diff
Plug 'mhinz/vim-signify'

" Show the git message
" Plug 'rhysd/git-messenger.vim'

" Tmux
Plug 'benmills/vimux'
" Plug 'tmux-plugins/vim-tmux'
" Plug 'christoomey/vim-tmux-navigator'

" Snippets
" Plug 'SirVer/ultisnips'
" Plug 'honza/vim-snippets'

" LSP and Complete: https://raw.githubusercontent.com/prabirshrestha/dotfiles/master/.vimrc
" Plug 'prabirshrestha/vim-lsp'
" Plug 'mattn/vim-lsp-settings'
" Plug 'prabirshrestha/asyncomplete.vim'
" Plug 'prabirshrestha/asyncomplete-lsp.vim'
" Plug 'prabirshrestha/asyncomplete-ultisnips.vim'

" Lang
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
" Plug 'gh-liu/gotests.vim'
" Plug 'rust-lang/rust.vim'

" TypeScript
" Plug 'herringtondarkholme/yats.vim'
" Plug 'maxmellon/vim-jsx-pretty'

Plug 'aklt/plantuml-syntax'
if executable('java')
  Plug 'scrooloose/vim-slumlord'
endif

" Plug 'stephpy/vim-yaml'
" Plug 'elzr/vim-json', {'for' : 'json'}
Plug 'cespare/vim-toml', {'for' : 'toml'}
Plug 'uarun/vim-protobuf'
Plug 'ekalinin/Dockerfile.vim', {'for' : 'Dockerfile'}

Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
  let g:vim_markdown_folding_disabled = 1
Plug 'iamcco/markdown-preview.nvim', { 'do': ':call mkdp#util#install()', 'for': 'markdown', 'on': 'MarkdownPreview' }
Plug 'mzlogin/vim-markdown-toc'
  let g:vmt_fence_text = 'TOC'
  let g:vmt_fence_closing_text = '/TOC'

" Plug 'lambdalisue/vim-backslash', { 'for': 'vim' }
" 	let g:vim_backslash#preventers = [
" 	      \ { -> context_filetype#get_filetype() !=# 'vim' },
" 	      \]
" Plug 'Shougo/context_filetype.vim'

" Writing
" Plug 'junegunn/limelight.vim'
  " let g:limelight_conceal_ctermfg=244
" Plug 'junegunn/goyo.vim'

" Misc
" Show keymaps begin with <leader>
" Plug 'liuchengxu/vim-which-key', { 'on': ['WhichKey', 'WhichKey!'] }
" if has_key(g:plugs, 'vim-which-key')
"   nnoremap <silent> <leader> :WhichKey ','<CR>
" endif

" Plug 'szw/vim-smartclose'
" if has_key(g:plugs, 'vim-smartclose')
"   let g:smartclose_default_mapping_key = '<leader>c'
" endif

" Run a diff on 2 blocks of text.
Plug 'AndrewRadev/linediff.vim'

" Vim sugar for the UNIX shell commands
Plug 'tpope/vim-eunuch'

" For making Vim plugins
Plug 'tpope/vim-scriptease'
" Plug 'junegunn/vader.vim'

" Share Code 
" Plug 'junegunn/vim-carbon-now-sh', { 'on': 'CarbonNowSh' }

" Plug 'chrisbra/unicode.vim', {'on': ['UnicodeName', 'UnicodeTable']}
"
" Plug 'tyru/open-browser.vim'
"   let g:netrw_nogx = 1 " disable netrw's gx mapping.
"   nmap gx <Plug>(openbrowser-smart-search)
"   vmap gx <Plug>(openbrowser-smart-search)

" Run a diff on 2 directories.
" Plug 'will133/vim-dirdiff'

" Automatically clear search highlights after you move your cursor.
" Plug 'haya14busa/is.vim'

" Better display unwanted whitespace.
" Plug 'ntpeters/vim-better-whitespace'

" Plug 'editorconfig/editorconfig-vim'

" Plug 'romainl/vim-qf'

" Tab management for Vim
" Plug 'kien/tabman.vim'

" Modern database interface for Vim
" Plug 'tpope/vim-dadbod'

Plug 'matt-deacalion/vim-systemd-syntax'

call plug#end()


" == Color == {{{1
" Enable 24-bit true colors if your terminal supports it.
if (has("termguicolors"))
  " https://github.com/vim/vim/issues/993#issuecomment-255651605
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

  set termguicolors
endif

" Enable syntax highlighting.
syntax on

" Set the color scheme.
colorscheme gruvbox
set background=dark


" == Status Line == {{{1
set laststatus=2
" https://github.com/junegunn/dotfiles/blob/83a40932cac993925176c830d332f68ef445a19a/vimrc#L268
function! s:statusline_expr()
  let mod = "%{&modified ? '[+] ' : !&modifiable ? '[x] ' : ''}"
  let ro  = "%{&readonly ? '[RO] ' : ''}"
  let ft  = "%{len(&filetype) ? '['.&filetype.'] ' : '[No ft]'}"
  " let ff  = "%{len(&fileformat) ? '['.&fileformat.'] ' : ''}"
  " let fe  = "%{len(&fileencoding) ? '['.&fileencoding.'] ' : ''}"
  let fug = "%{exists('g:loaded_fugitive') ? fugitive#statusline() : ''}"
  let sgf = "%{exists('g:loaded_signify') ? sy#repo#get_stats_decorated() : ''}"
  let sep = ' %= '
  let pos = ' %-12(%l/%L : %c%V%) '
  let pct = ' %P'

  return '[%n] %F %<'.mod.ro.ft.fug.sep.sgf.pos.'%*'.pct
endfunction
let &statusline = s:statusline_expr()

" == Tab Line == {{{1
function! Tabline()
  let s = ''
  for i in range(tabpagenr('$'))
    " range() start from 0, but the number of tab start from 1.
    let tabnr = i + 1 
    " Gets current window of current tab.
    let winnr = tabpagewinnr(tabnr)
    " Each item in the list is the number of the buffer associated with each windows in the current tab.
    let buflist = tabpagebuflist(tabnr)
    " Gets current buffer number.
    let bufnr = buflist[winnr - 1]
    " Gets the name of the current buffer in the current window of the current tab.
    let bufname = bufname(bufnr)

    " Use "%1T" for the first tab, etc.
    let s .= '%' . tabnr . 'T' 
    " Highlight the current tab
    let s .= (tabnr == tabpagenr() ? '%#TabLineSel#' : '%#TabLine#')
    " Current tab number
    let s .= ' ' . tabnr .':'
    let s .= (bufname != '' ? '['. fnamemodify(bufname, ':t') . '] ' : '[No Name] ')
    " Append '[+]' if the buffer of the current tab modified
    let bufmodified = getbufvar(bufnr, "&mod")
    if bufmodified
      let s .= '[+] '
    endif
  endfor

  let s .= '%#TabLineFill#'
  " Use "%X" items for the closing labels.
  let s .= '%=%999XX'
  return s
endfunction
set tabline=%!Tabline()

" hi TabLine      ctermfg=Black  ctermbg=Green     cterm=NONE
" hi TabLineFill  ctermfg=Black  ctermbg=Green     cterm=NONE
" hi TabLineSel   ctermfg=White  ctermbg=DarkBlue  cterm=NONE


" == Basic Settings == {{{1
let mapleader      = ','
let maplocalleader = ','

set nocompatible

set encoding=utf8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1

set autoread
set autowrite

set history=5000
set mouse=a

" set cursorline
" set cursorcolumn

set magic
set hlsearch
set incsearch
set ignorecase

set shiftwidth=4
set tabstop=4
set expandtab
set smarttab

set autoindent
set smartindent

set number
set relativenumber

set so=10
set ruler
set wildmenu
set showcmd
set cmdheight=2

set pumheight=10
set completeopt=longest,menu
set complete-=i   " disable scanning included files
set complete-=t   " disable searching tags

set nobackup
set nowb
set noswapfile

set foldenable
set foldmethod=indent
set foldlevel=99

set ttyfast
set lazyredraw

set hidden
set shortmess+=c

set updatetime=300
set noerrorbells

set splitright
set splitbelow

" set notimeout
" set ttimeout
set timeoutlen=320

set tags=./tags;/

set modelines=2
" set colorcolumn=80
set grepformat=%f:%l:%c:%m,%f:%l:%m
if executable('rg')
  set grepprg=rg\ --no-heading\ --vimgrep
endif

filetype on
filetype indent on
filetype plugin on
filetype plugin indent on

if has("nvim-0.5.0") || has("patch-8.1.1564")
  " Merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif


" == Basic mappings == {{{1
nnoremap <F1> <Esc>
inoremap <F1> <Esc>
vnoremap <F1> <Esc>

" Ctrl+c as Esc
nnoremap <C-c> <Esc>
inoremap <C-c> <Esc>
vnoremap <C-c> <Esc>
snoremap <C-c> <Esc>
xnoremap <C-c> <Esc>
cnoremap <C-c> <Esc>
onoremap <C-c> <Esc>
lnoremap <C-c> <Esc>
tnoremap <C-c> <Esc>

" map <space> <leader>

" Disable CTRL-F for Tmux
nnoremap <C-f> <nop>
nmap <Leader><C-f> <C-f>

" nnoremap ; :
" nnoremap <leader>; ;

" Switch ` and '
" By default, ' jumps to the marked line, ` jumps to the marked line and columnm
nnoremap ' `
nnoremap ` '

nnoremap [w :tabprevious<cr>
nnoremap ]w :tabnext<cr>
nnoremap [W :tabfirst<cr>
nnoremap ]W :tablast<cr>

nnoremap [b :bprevious<cr>
nnoremap ]b :bnext<cr>
nnoremap [B :bfirst<cr>
nnoremap ]B :blast<cr>

nnoremap [l :lprevious<cr>
nnoremap ]l :lnext<cr>
nnoremap [L :lfirst<cr>
nnoremap ]L :llast<cr>

nnoremap [q :cprevious<cr>
nnoremap ]q :cnext<cr>
nnoremap [Q :cfirst<cr>
nnoremap ]Q :clast<cr>

nnoremap [t :tprevious<cr>
nnoremap ]t :tnext<cr>
nnoremap [T :tfirst<cr>
nnoremap ]T :tlast<cr>

" <Leader>[1-9] move to tab [1-9]
for s:i in range(1, 9)
  execute 'nnoremap <Leader>' . s:i . ' ' . s:i . 'gt'
endfor

" Move current window to a new tab
nnoremap <Leader>wt <C-w>T

" Quickly move current line
nnoremap [e  :move-2<cr>
nnoremap ]e  :move+1<cr>

nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-h> <C-W>h
nmap <C-l> <C-W>l

cnoremap <C-h> <left>
cnoremap <C-j> <down>
cnoremap <C-k> <up>
cnoremap <C-l> <right>
cnoremap <C-a> <HOME>

inoremap <C-h> <left>
inoremap <C-j> <down>
inoremap <C-k> <up>
inoremap <C-l> <right>
imap <C-a> <HOME>
imap <C-e> <END>

" noremap <Up> gk
" noremap <Down> gj
noremap j gj
noremap k gk

noremap $ g$
noremap 0 g0

nnoremap H ^
nnoremap L $
vnoremap H ^
vnoremap L g_

" Edit alternate file
inoremap <C-^> <C-o><C-^>

" Save
inoremap <C-s> <C-O>:update<cr>
nnoremap <C-s> :update<cr>

" Exit
inoremap <C-q> <esc>:q<cr>
nnoremap <C-q> :q<cr>
vnoremap <C-q> <esc>
nnoremap <Leader>q :q<cr>
nnoremap <Leader>Q :qa!<cr>

" <Leader>c Close quickfix/location window
nnoremap <silent> <leader>c :cclose<bar>lclose<CR>
" nnoremap <leader>cq :cclose<cr>
" nnoremap <leader>cl :lclose<cr>


" Esc quickly
imap jj <Esc>
imap jk <Esc>

" qq to record, Q to replay
nnoremap Q @q

" same as D
nnoremap Y y$

" Search the visual block
vnoremap // y/<c-r>"<cr>

" Toggle highlight
noremap <silent><leader>/ :set nohls!<CR>
noremap <silent><leader><leader>/ :let @/ = ""<CR>

" Keep search pattern at the center of the screen
nnoremap <silent> n nzz
nnoremap <silent> N Nzz
" Switch # *
nnoremap <silent> * #zz
nnoremap <silent> # *zz

" Change window size
nnoremap <left>   <c-w>>
nnoremap <right>  <c-w><
nnoremap <up>     <c-w>-
nnoremap <down>   <c-w>+

nnoremap <leader>o o<esc>
nnoremap <leader>O O<esc>

" Do not show stupid q: window
map q: :q

" Edit vimrc
nnoremap <leader>ev :tabnew $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Press * to search for the term under the cursor or a visual selection and
" then press a key below to replace all instances of it in the current file.
nnoremap <Leader>r :%s///g<Left><Left>
nnoremap <Leader>rc :%s///gc<Left><Left><Left>
xnoremap <Leader>r :s///g<Left><Left>
xnoremap <Leader>rc :s///gc<Left><Left><Left>

" Remove whitespace
noremap <silent><leader>CW :%s/\s\+$//<CR>

" Don't lose selection when shifting sidewards
xnoremap <  <gv
xnoremap >  >gv

" terminal
" tnoremap <Esc> <C-\><C-n>
tnoremap <expr> <Esc> (&filetype == "fzf") ? "<Esc>" : "<c-\><c-n>"

vnoremap J j

" https://github.com/junegunn/dotfiles/blob/057ee47465e43aafbd20f4c8155487ef147e29ea/vimrc#L1027
" co? : Toggle options (inspired by unimpaired.vim)
function! s:map_change_option(...)
  let prefix = 'co'
  let [key, opt] = a:000[0:1]
  let op = get(a:, 3, 'set '.opt.'!')
  execute printf("nnoremap %s%s :%s<bar>set %s?<cr>", prefix, key, op, opt)
endfunction

call s:map_change_option('p', 'paste')
" call s:map_change_option('n', 'number')
call s:map_change_option('w', 'wrap')
call s:map_change_option('h', 'hlsearch')
call s:map_change_option('m', 'mouse', 'let &mouse = &mouse == "" ? "a" : ""')
call s:map_change_option('t', 'textwidth',
    \ 'let &textwidth = input("textwidth (". &textwidth ."): ")<bar>redraw')
call s:map_change_option('b', 'background',
    \ 'let &background = &background == "dark" ? "light" : "dark"<bar>redraw')

" https://github.com/mhinz/vim-galore#quickly-edit-your-macros
" Quickly edit macros, Use it like this <leader>m or "q<leader>m(Note the sign `"`).
nnoremap <leader>m  :<c-u><c-r><c-r>='let @'. v:register .' = '. string(getreg(v:register))<cr><c-f><left>

" Use space close/open flod
nnoremap <silent> <space> @=(foldlevel('.')?'za':"\<space>")<CR>

function! ToogleNumber()
  if (&relativenumber == &number)
    set relativenumber! number!
  elseif (&number)
    set number!
  else
    set relativenumber!
  endif
    set number?
endfun
function! ToggleSignColumn()
  if &number
    set signcolumn=number
  else
    set signcolumn=no
  endif
endfun
function! ToggleSignColumnAndNumber()
  call ToogleNumber()
  call ToggleSignColumn()
endfun
nnoremap <F2> :call ToggleSignColumnAndNumber()<CR>

" ]p to paste into a newline
" [p to paste into the line upon cursor
" https://github.com/tpope/vim-unimpaired/blob/master/plugin/unimpaired.vim#L343
" function! s:putline(how, map) abort
"   let [body, type] = [getreg(v:register), getregtype(v:register)]
"   if type ==# 'V'
"     exe 'normal! "'.v:register.a:how
"   else
"     call setreg(v:register, body, 'l')
"     exe 'normal! "'.v:register.a:how
"     call setreg(v:register, body, type)
"   endif
"     silent! call repeat#set("\<Plug>unimpairedPut".a:map)
" endfunction
" nnoremap <silent> [p :call <SID>putline('[p', 'Above')<CR>
" nnoremap <silent> ]p :call <SID>putline(']p', 'Below')<CR>

" Echo the number under the cursor as binary, useful for bitwise operations
function! s:echoBinary()
  echo printf("%08b", expand('<cword>'))
endfunction
nnoremap <silent> gb :<C-u>call <SID>echoBinary()<CR>

" == Basic autocommands == {{{1

augroup vimrc
  " Open netrw if no files provided
  " autocmd VimEnter * if argc() == 0 | Explore! | endif

  " http://vim.wikia.com/wiki/Highlight_unwanted_spaces
  " autocmd BufNewFile,BufRead,InsertLeave * silent! match ExtraWhitespace /\s\+$/
  " autocmd InsertEnter * silent! match ExtraWhitespace /\s\+\%#\@<!$/

  " Enter automatically into the files directory
  " autocmd BufEnter * silent! lcd %:p:h

  " resize splits
  autocmd VimResized * wincmd =

  " quickfix window on very bottom
  autocmd FileType qf wincmd J 

  " https://vim.fandom.com/wiki/Automatically_quit_Vim_if_quickfix_window_is_the_last
  autocmd BufEnter * if (&buftype=="quickfix" && winnr('$') < 2 ) | quit! | endif 

  " Automatic rename of tmux window
  if exists('$TMUX') && !exists('$NORENAME')
    autocmd BufEnter * if empty(&buftype) | call system('tmux rename-window '.expand('%:t:S')) | endif
    autocmd VimLeave * call system('tmux set-window automatic-rename on')
  endif
  
  " Only show the cursor line in the active buffer.
  au VimEnter,WinEnter,BufWinEnter * setlocal cursorline cursorcolumn
  au WinLeave * setlocal nocursorline nocursorcolumn
augroup END

" Open help page in a new tab
function! s:helptab()
  if &buftype == 'help'
  wincmd T
  nnoremap <buffer> q :q<cr>
  endif
endfun
"Open plug github repo in browser by press <CR>
function! s:goto_github()
  let s:repo = matchstr(expand("<cWORD>"), '\v[0-9A-Za-z\-\_\.]+/[0-9A-Za-z\-\_\.]+')
  if empty(s:repo)
    echo "GoToGithub: No repository found."
  else
    let s:url = 'https://github.com/' . s:repo
    call netrw#BrowseX(s:url, 0)
  end
endfun
function! s:setNorelativenumber()
  " if it's number , set norelativenumber
  if (&number == 1)
  set norelativenumber
  endif
endfun
function! s:setRelativenumber()
  " if it's number , set relativenumber
  if (&number == 1)
  set relativenumber
  endif
endfun

augroup myfunc
  autocmd!
  " if executable('ibus')
  " autocmd InsertLeave * call system("CIMTE")
  " endif

  autocmd BufEnter *.txt call s:helptab()
  autocmd InsertEnter * call s:setNorelativenumber()
  autocmd InsertLeave * call s:setRelativenumber()

  " autocmd FileType *vim,*zsh,*bash,*tmux nnoremap <buffer> <silent> <cr> :call <sid>goto_github()<cr>
  autocmd FileType *vim,*zsh,*bash,*tmux command! GOTOGITHUB call s:goto_github()
augroup END

augroup myhl
  autocmd!
  " Highlight TODO, FIXME, NOTE, etc.
  if v:version > 701
    autocmd Syntax * call matchadd('Todo',  '\W\zs\(TODO\|FIXME\|CHANGED\|DONE\|XXX\|BUG\|HACK\)')
    autocmd Syntax * call matchadd('Debug', '\W\zs\(NOTE\|INFO\|IDEA\|NOTICE\)')
  endif
augroup END

augroup myfiletype
  autocmd!
  autocmd FileType vim setlocal foldmethod=marker
  autocmd FileType tmux setlocal foldmethod=marker

  autocmd FileType json setlocal expandtab shiftwidth=2 tabstop=2
  autocmd FileType yaml setlocal expandtab shiftwidth=2 tabstop=2
  autocmd FileType go setlocal noexpandtab tabstop=4 shiftwidth=4

  autocmd BufNewFile,BufRead *.sh setlocal expandtab shiftwidth=2 tabstop=2
  autocmd BufNewFile,BufRead *.vim setlocal expandtab shiftwidth=2 tabstop=2
  autocmd BufNewFile,BufRead *.proto setlocal expandtab shiftwidth=2 tabstop=2


  autocmd BufRead,BufNewFile Vagrantfile set filetype=ruby
augroup END

if !v:vim_did_enter && has('reltime')
  let g:startuptime = reltime()
  augroup vimrc-startuptime
  autocmd! VimEnter * ++once
  \        let g:startuptime = reltime(g:startuptime)
  \        | redraw
  \        | echomsg 'startuptime: ' .. reltimestr(g:startuptime)
  augroup END
endif



" == Basic commands == {{{1
" Add all TODO items to the quickfix list relative to where you opened Vim.
function! s:todo() abort
  let entries = []
  for cmd in ['git grep -niIw -e TODO -e FIXME 2> /dev/null',
            \ 'grep -rniIw -e TODO -e FIXME . 2> /dev/null']
    let lines = split(system(cmd), '\n')
    if v:shell_error != 0 | continue | endif
    for line in lines
      let [fname, lno, text] = matchlist(line, '^\([^:]*\):\([^:]*\):\(.*\)')[1:3]
      call add(entries, { 'filename': fname, 'lnum': lno, 'text': text })
    endfor
    break
  endfor

  if !empty(entries)
    call setqflist(entries)
    copen
  endif
endfunction
command! Todo call s:todo()

" Export all vim mappings
function! s:export_all_mappings()
  redir! > vim_keys.txt
  silent verbose map
  redir END
endfun
command! ExportAllMappings call s:export_all_mappings()

" Change directory to the root of the Git repository
function! s:root()
  let root = systemlist('git rev-parse --show-toplevel')[0]
  if v:shell_error
    echo 'Not in git repo'
  else
    execute 'lcd' root
    echo 'Changed directory to: '.root
  endif
endfunction
command! Root call s:root()

" Profile
function! s:profile(bang)
  if a:bang
    profile pause
    noautocmd qall
  else
    profile start /tmp/profile.log
    profile func *
    profile file *
  endif
endfunction
command! -bang Profile call s:profile(<bang>0)

" Full screen support
if executable("wmctrl") && executable("xdotool")
  command! FullScreenToggle call system("wmctrl -ir $(xdotool getwindowfocus) -b toggle,fullscreen")
endif

" Notes! Need set $NOTES_DIR in shell.
function! Note(...)
  if a:0 > 0
    let l:path = $NOTES_DIR ."/". strftime("%Y%m%d%H%M")."_".trim(join(a:000)).".md"
    execute (@% == "" ? "edit" : "tabedit") fnameescape(l:path)
    execute "norm" "i# ".trim(join(a:000))
    execute "norm" "o"
    execute "norm" "o"
  else
    call fzf#vim#files($NOTES_DIR, {'options': ['--with-nth', '2..']}, 0)
  end
endfunction
command! -nargs=* Note call Note(<f-args>)
command! SearchNotes call fzf#run(fzf#wrap({'source': 'rg -t md -l --files', 'options': ['--bind', 'change:reload:rg -t md -l {q}', '--phony', '--with-nth', '2..'], 'dir': $NOTES_DIR, 'sink': 'edit'}))


" == Plugins Config == {{{1
" gruvbox
if !exists('g:gruvbox_contrast_dark')
  let g:gruvbox_contrast_dark='hard'
endif
if (g:colors_name == 'gruvbox')
  if (&background == 'dark')
     hi Visual cterm=NONE ctermfg=NONE ctermbg=214 guifg=#282828 guibg=#fabd2f
  else
    " hi Visual cterm=NONE ctermfg=NONE ctermbg=228 guibg=#f2e5bc
    " hi CursorLine cterm=NONE ctermfg=NONE ctermbg=228 guibg=#f2e5bc
    " hi ColorColumn cterm=NONE ctermfg=NONE ctermbg=228 guibg=#f2e5bc
  endif
endif

if has_key(g:plugs, 'rainbow_parentheses.vim')
  let g:rainbow#blacklist = [121]
  let g:rainbow#pairs = [['(', ')'], ['[', ']'], ['{', '}']]

  autocmd VimEnter * RainbowParentheses
endif

if has_key(g:plugs, 'vim-signature')
  let g:SignatureMap = {
        \ 'Leader'             :  "m",
        \ 'PlaceNextMark'      :  "m,",
        \ 'ToggleMarkAtLine'   :  "m.",
        \ 'PurgeMarksAtLine'   :  "m-",
        \ 'DeleteMark'         :  "dm",
        \ 'PurgeMarks'         :  "m<Space>",
        \ 'PurgeMarkers'       :  "m<BS>",
        \ 'GotoNextLineAlpha'  :  "']",
        \ 'GotoPrevLineAlpha'  :  "'[",
        \ 'GotoNextSpotAlpha'  :  "`]",
        \ 'GotoPrevSpotAlpha'  :  "`[",
        \ 'GotoNextLineByPos'  :  "]'",
        \ 'GotoPrevLineByPos'  :  "['",
        \ 'GotoNextSpotByPos'  :  "]`",
        \ 'GotoPrevSpotByPos'  :  "[`",
        \ 'GotoNextMarker'     :  "]-",
        \ 'GotoPrevMarker'     :  "[-",
        \ 'GotoNextMarkerAny'  :  "]=",
        \ 'GotoPrevMarkerAny'  :  "[=",
        \ 'ListBufferMarks'    :  "m/",
        \ 'ListBufferMarkers'  :  "m?"
        \ }
endif

if has_key(g:plugs, 'vim-commentary')
    autocmd FileType toml setlocal commentstring=#\ %s
  " vim registers <C-/> as <C-_>
    nmap <C-_> gcc
    imap <C-_> <C-O>gcc
    vmap <C-_> gc
endif

if has_key(g:plugs, 'splitjoin.vim')
  let g:splitjoin_split_mapping = ''
  let g:splitjoin_join_mapping = ''
  nnoremap gss :SplitjoinSplit<cr>
  nnoremap gsj :SplitjoinJoin<cr>
endif

" if has_key(g:plugs, 'switch.vim')
"   let g:switch_mapping = '_'
"   let g:switch_custom_definitions = [
"     \   ['MON', 'TUE', 'WED', 'THU', 'FRI'],
"     \   ['ture', 'false']
"     \ ]
" endif

" if has_key(g:plugs, 'vim-easy-align')
"     vmap <Leader>a <Plug>(EasyAlign)
"     nmap <Leader>a <Plug>(EasyAlign)
" endif

if has_key(g:plugs, 'vim-easymotion')
  let g:EasyMotion_do_mapping = 0
  let g:EasyMotion_smartcase = 1
  let g:EasyMotion_enter_jump_first = 1 

  nmap f <Plug>(easymotion-s)
  nmap F <Plug>(easymotion-bd-w)

  map <Leader><leader>. <Plug>(easymotion-repeat)
  map <Leader><leader>h <Plug>(easymotion-linebackward)
  map <Leader><leader>l <Plug>(easymotion-lineforward)
  map <Leader><Leader>j <Plug>(easymotion-j)
  map <Leader><Leader>k <Plug>(easymotion-k)

  map <Leader><Leader>W <Plug>(easymotion-W)
  map <Leader><Leader>w <Plug>(easymotion-w)
  map <Leader><Leader>N <Plug>(easymotion-N)
  map <Leader><Leader>n <Plug>(easymotion-n)
endif

" if has_key(g:plugs, 'ctrlsf.vim')
"   " let g:ctrlsf_default_view_mode = 'compact'
"   let g:ctrlsf_auto_focus = {
"         \ "at": "start",
"         \ }
"     nmap     <leader>ff <Plug>CtrlSFPrompt
"     vmap     <leader>ff <Plug>CtrlSFVwordPath
"     vmap     <leader>fF <Plug>CtrlSFVwordExec
"     nmap     <leader>fw <Plug>CtrlSFCwordPath
"     nmap     <leader>fW <Plug>CtrlSFCwordExec
"     nnoremap   <leader>ft :CtrlSFToggle<CR>
" endif

if has_key(g:plugs, 'fzf.vim')
  let $FZF_DEFAULT_OPTS .= ' --inline-info'

  let g:fzf_colors =
    \ { 'fg':      ['fg', 'Normal'],
    \ 'bg':      ['bg', 'Normal'],
    \ 'hl':      ['fg', 'Comment'],
    \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
    \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
    \ 'hl+':     ['fg', 'Statement'],
    \ 'info':    ['fg', 'PreProc'],
    \ 'border':  ['fg', 'Ignore'],
    \ 'prompt':  ['fg', 'Conditional'],
    \ 'pointer': ['fg', 'Exception'],
    \ 'marker':  ['fg', 'Keyword'],
    \ 'spinner': ['fg', 'Label'],
    \ 'header':  ['fg', 'Comment'] }
  
  " See `man fzf-tmux` for available options
  " if exists('$TMUX')
  "   let g:fzf_layout = { 'tmux': '-p90%,60%' , 'relative': v:true}
  " else
  "   let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
  " endif
  let g:fzf_layout = { 'down': '~25%' }

  nnoremap <C-p> :Files<cr>
  inoremap <C-p> <esc>:<C-u>Files<cr>

  nnoremap <silent> <Leader>L :Lines<CR>
  nnoremap <silent> <Leader>C :Colors<CR>
  nnoremap <silent> <Leader>` :Marks<CR>
  nnoremap <silent> <Leader><Enter> :Buffers<CR>

  " Allow passing optional flags into the Rg command. Example: :Rg myterm -g '*.md'
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \ "rg --column --line-number --no-heading --color=always --smart-case " .
    \ <q-args>, 1, fzf#vim#with_preview(), <bang>0)

  nnoremap <leader>FF :Rg  -g '*'<left><left><left><left><left><left><left>
  nnoremap <leader>ff :Rg 
  xnoremap <silent> <Leader>ff y:Ag <C-R>"<CR>
  nnoremap <silent> <leader>fw :call <SID>search_word_underline()<CR>
  function! s:search_word_underline() abort
    let l:cw = expand('<cword>')
    execute 'Rg ' . l:cw
  endfun

  augroup fzf-conf
    autocmd!
    " Hide statusline
    " autocmd! FileType fzf set laststatus=0 noshowmode noruler
    " \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler
  augroup END

endif

if has_key(g:plugs, 'coc.nvim')
  " set tagfunc=CocTagFunc

  " Make <CR> auto-select the first completion item and notify coc.nvim to
  " format on enter, <cr> could be remapped by other vim plugin
  " inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
  "                               \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

  " Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
  " position. Coc only does snippet and additional edit on confirm.
  " <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
  " if exists('*complete_info')
  "   inoremap <silent><expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u"
  " else
  "   inoremap <silent><expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u<CR>"
  " endif

  inoremap <silent><expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u<CR>"

  " Use <tab> for trigger completion and navigate to the next complete item
  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
  endfunction
  " inoremap <silent><expr> <TAB>
  "       \ pumvisible() ? "\<C-n>" :
  "       \ <SID>check_back_space() ? "\<TAB>" :
  "       \ coc#refresh()
    inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
  " Use <S-Tab> navigate to the previous complete item
    inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

  " Make <tab> used for trigger completion, completion confirm, snippet expand and jump like VSCode.
  " https://github.com/neoclide/coc-snippets
  let g:coc_snippet_next = '<tab>'

  " Use K to show documentation
  nnoremap <silent> K :call <SID>show_documentation()<CR>
  function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
      execute 'h '.expand('<cword>')
    elseif (coc#rpc#ready())
      call CocActionAsync('doHover')
    else
      execute '!' . &keywordprg . " " . expand('<cword>')
    endif
  endfunction

  " Extensions for CoC
  let g:coc_global_extensions = [
      \'coc-snippets',
      \'coc-pairs',
      \'coc-yaml',
      \'coc-json',
      \'coc-lua',
      \'coc-jedi',
      \'coc-go',
      \'coc-tsserver',
      \'coc-prettier',
      \'coc-eslint',
      \'coc-vimlsp'
      \]

    augroup coc-conf
      autocmd!
      nmap <C-a> <C-o>
      nmap <C-d> <plug>(coc-definition)

      autocmd VimEnter * nnoremap <silent><nowait>gh :call CocActionAsync('doHover')<CR>
      autocmd VimEnter * nnoremap <silent><nowait>gd :call CocActionAsync('jumpDefinition')<CR>
      autocmd VimEnter * nnoremap <silent><nowait>gD :call CocActionAsync('jumpDefinition', 'vsplit')<CR>
      " autocmd VimEnter * nmap <silent> gd <Plug>(coc-definition)
      autocmd VimEnter * nmap <silent> gy <Plug>(coc-type-definition)
      autocmd VimEnter * nmap <silent> gi <Plug>(coc-implementation)
      autocmd VimEnter * nmap <silent> gr <Plug>(coc-references)

      autocmd VimEnter * nmap <silent> <leader>rn <Plug>(coc-rename)
      autocmd VimEnter * nmap <silent> <leader>rf <Plug>(coc-refactor)
      autocmd VimEnter * nmap <silent> <leader>ca <Plug>(coc-codeaction)
      autocmd VimEnter * nmap <silent> <leader>cs <Plug>(coc-codeaction-selected)
      autocmd VimEnter * nmap <silent> <leader>fc <Plug>(coc-fix-current)

      autocmd VimEnter * nmap <silent> [d <Plug>(coc-diagnostic-prev)
      autocmd VimEnter * nmap <silent> ]d <Plug>(coc-diagnostic-next)

      " Update signature help on jump placeholder.
      " autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')

      " Highlight the symbol and its references when holding the cursor.
      highlight CocHighlightText term=underline cterm=underline gui=underline
      autocmd CursorHold * silent call CocActionAsync('highlight')
    augroup END

    " Add `:Format` command to format current buffer.
    command! -nargs=0 Format :call CocAction('format')

    " Add some commands for Go
    " command! -nargs=0 GoGenTestFile :call CocAction('runCommand', 'go.test.generate.file')
    " command! -nargs=0 GoGenTestFunc :call CocAction('runCommand', 'go.test.generate.function')
    " command! -nargs=0 GoGenTestExpo :call CocAction('runCommand', 'go.test.generate.exported')
    " command! -nargs=0 GoTestToggle  :call CocAction('runCommand', 'go.test.toggle')

  " " Mappings for CoCList
  " " Show all diagnostics.
  "   nnoremap <silent><nowait> <space>d  :<C-u>CocList --normal diagnostics<cr>
  " " Manage extensions.
  "   nnoremap <silent><nowait> <space>e  :<C-u>CocList --normal extensions<cr>
  " " Show commands.
  "   nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
  " " Find symbol of current document.
  "   nnoremap <silent><nowait> <space>o  :<C-u>CocList --normal outline<cr>
  " " Search workspace symbols.
  "   nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
  " " open yank list
  " " nnoremap <silent> <space>y  :<C-u>CocList -A --normal yank<cr>
  " " Do default action for next item.
  "   nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
  " " Do default action for previous item.
  "   nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
  " " Resume latest coc list.
  "   nnoremap <silent><nowait> <space>p :<C-u>CocListResume<CR>
endif

if has_key(g:plugs, 'tagbar')
  let g:tagbar_autoclose = 1
  let g:tagbar_autofocus = 1
  let g:tagbar_position = 'leftabove vertical'
  let g:tagbar_width = 30
  " let g:tagbar_sort = 0
  let g:tagbar_compact = 1
  nnoremap T :TagbarToggle<CR>

  " https://github.com/preservim/tagbar/wiki#markdown
  let g:tagbar_type_markdown = {
    \ 'ctagstype'	: 'markdown',
    \ 'kinds'		: [
        \ 'c:chapter:0:1',
        \ 's:section:0:1',
        \ 'S:subsection:0:1',
        \ 't:subsubsection:0:1',
        \ 'T:l4subsection:0:1',
        \ 'u:l5subsection:0:1',
    \ ],
    \ 'sro'			: '""',
    \ 'kind2scope'	: {
        \ 'c' : 'chapter',
        \ 's' : 'section',
        \ 'S' : 'subsection',
        \ 't' : 'subsubsection',
        \ 'T' : 'l4subsection',
    \ },
    \ 'scope2kind'	: {
        \ 'chapter' : 'c',
        \ 'section' : 's',
        \ 'subsection' : 'S',
        \ 'subsubsection' : 't',
        \ 'l4subsection' : 'T',
    \ },
    \ }

"   let g:tagbar_type_json = {
"     \ 'ctagstype' : 'json',
"     \ 'kinds' : [
"       \ 'o:objects',
"       \ 'a:arrays',
"       \ 'n:numbers',
"       \ 's:strings',
"       \ 'b:booleans',
"       \ 'z:nulls'
"     \ ],
"   \ 'sro' : '.',
"     \ 'scope2kind': {
"     \ 'object': 'o',
"       \ 'array': 'a',
"       \ 'number': 'n',
"       \ 'string': 's',
"       \ 'boolean': 'b',
"       \ 'null': 'z'
"     \ },
"     \ 'kind2scope': {
"     \ 'o': 'object',
"       \ 'a': 'array',
"       \ 'n': 'number',
"       \ 's': 'string',
"       \ 'b': 'boolean',
"       \ 'z': 'null'
"     \ },
"     \ 'sort' : 0
"     \ }
endif

if has_key(g:plugs, 'undotree')
  let g:undotree_SetFocusWhenToggle = 1
  let g:undotree_WindowLayout = 2
  nnoremap U :UndotreeToggle<CR>
endif

if has_key(g:plugs, 'vim-fugitive')
  nmap <leader>gb :Gblame<CR>
  vmap <leader>gb :Gblame<CR>
  nmap <leader>gl :tabe %<CR>:Glog -- %<CR>
endif

if has_key(g:plugs, 'vim-signify')
  let g:signify_disable_by_default = 1
  let g:signify_vcs_list = ['git']
  nnoremap <leader>gt :SignifyToggle<CR>
  nnoremap <leader>gd :SignifyHunkDiff<CR>
  nnoremap <leader>gu :SignifyHunkUndo<CR>

  if (g:colors_name == 'gruvbox')
    highlight SignifySignAdd    ctermfg=142   guifg=#b8bb26 cterm=NONE gui=NONE
    highlight SignifySignDelete ctermfg=167    guifg=#fb4934 cterm=NONE gui=NONE
    highlight SignifySignChange ctermfg=108 guifg=#8ec07c cterm=NONE gui=NONE
  endif
endif

" if has_key(g:plugs, 'vim-gutentags')
"   let g:gutentags_enabled=0
" endif

if has_key(g:plugs, 'vim-go')
  " Go syntax highlighting
  let g:go_highlight_types = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_function_calls = 1
  let g:go_highlight_extra_types = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_generate_tags = 1
  let g:go_highlight_build_constraints = 1
  let g:go_highlight_debug = 0

  " Status line types/signatures
  let g:go_auto_type_info = 1

  " disable K
  let g:go_doc_keywordprg_enabled = 0

  " complete by coc.nvim
  let g:go_code_completion_enabled = 0

  let g:go_test_show_name = 1

  " run go imports on file save
  " let g:go_fmt_command = "goimports"

  let g:go_def_mapping_enabled = 0

  let g:go_debug_preserve_layout = 1
  let g:go_debug_windows = {
              \ 'vars':       'leftabove 30vnew',
              \ 'stack':      'leftabove 20new',
              \ 'goroutines': 'leftabove 10new',
              \ 'out':        'botright  5new',
    \ }
  let g:go_debug_mappings = {
      \ '(go-debug-stepout)':    {'key': '<F6>'},
      \ '(go-debug-step)':       {'key': '<F7>'},
      \ '(go-debug-next)':       {'key': '<F8>'},
      \ '(go-debug-continue)':   {'key': '<F9>'},
      \ '(go-debug-print)':      {'key': '<F10>'},
      \ }


  augroup vim-go-conf
    autocmd!
    autocmd FileType go nmap <silent> <leader>d  <Plug>(go-describe)

    autocmd FileType go nmap <silent> <leader>b   :GoDebugBreakpoint<cr>

    autocmd FileType go nmap <silent> <leader>B :<C-u>call <SID>build_go_files()<CR>

    autocmd FileType go nmap <silent> <Leader>td <Plug>(go-def-tab)
    " autocmd Filetype go
    "         \  command! -bang A call go#alternate#Switch(<bang>0, 'edit')
    "         \| command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
    "         \| command! -bang AS call go#alternate#Switch(<bang>0, 'split')

    " autocmd BufEnter *.go silent exe "GoGuruScope " . go#package#ImportPath() . "..."
  augroup END

  " run :GoBuild or :GoTestCompile based on the go file
  function! s:build_go_files()
    let l:file = expand('%')
    if l:file =~# '^\f\+_test\.go$'
        call go#test#Test(0, 1)
    elseif l:file =~# '^\f\+\.go$'
        call go#cmd#Build(0)
    endif
  endfunction

  if has('terminal')
    let g:go_term_enabled = 1
    let g:go_term_mode = "split"
  endif
endif

if has_key(g:plugs, 'vimux')
    nnoremap <Leader>vp :VimuxPromptCommand<CR>
    nnoremap <Leader>vc :VimuxCloseRunner<CR>
    nnoremap <Leader>vl :VimuxRunLastCommand<CR>
endif

if has_key(g:plugs, 'vim-visual-multi')
  let g:VM_maps = {}
  let g:VM_maps['Find Under']='<C-m>'
  let g:VM_maps['Find Subword Under']='<C-m>'
endif

if has_key(g:plugs, 'quick-scope')
  " Trigger a highlight in the appropriate direction when pressing these keys.
  let g:qs_highlight_on_keys=['f', 'F', 't', 'T']
  " Only underline the highlights instead of using custom colors.
  highlight QuickScopePrimary gui=underline cterm=underline
  highlight QuickScopeSecondary gui=underline cterm=underline
endif

if has_key(g:plugs, 'indentLine')
  autocmd! User indentLine doautocmd indentLine Syntax
  let g:indentLine_color_term = 239
  let g:indentLine_color_gui = '#616161'
  " resolve symbol " disappears for json files
  let g:vim_json_conceal = 0 
endif

if has_key(g:plugs, 'vim-qf')
endif

if has_key(g:plugs, 'vim-carbon-now-sh')
  let g:carbon_now_sh_options = { 't': 'oceanic-next'}
endif

if has_key(g:plugs, 'asyncomplete.vim')
  inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"

  function! s:check_back_space() abort
      let col = col('.') - 1
      return !col || getline('.')[col - 1]  =~ '\s'
  endfunction

  " inoremap <silent><expr> <TAB>
  "   \ pumvisible() ? "\<C-n>" :
  "   \ <SID>check_back_space() ? "\<TAB>" :
  "   \ asyncomplete#force_refresh()
  " inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

  set completeopt=menuone,noinsert,noselect,preview

  autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif

  if executable('gopls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'gopls',
        \ 'cmd': {server_info->['gopls','-remote','auto']},
        \ 'whitelist': ['go'],
        \ })
    autocmd BufWritePre *.go LspDocumentFormatSync
  endif

  " let g:UltiSnipsExpandTrigger="<c-e>"
  " call asyncomplete#register_source(asyncomplete#sources#ultisnips#get_source_options({
  "     \ 'name': 'ultisnips',
  "     \ 'allowlist': ['*'],
  "     \ 'completor': function('asyncomplete#sources#ultisnips#completor'),
  "     \ }))
endif

if has_key(g:plugs, 'vim-scriptease')
  function s:RTP() abort
    let plug_path = getcwd()
    execute 'Runtime' . plug_path . '/**/*.vim'
  endfunction

   autocmd FileType vim command! RTP call s:RTP()
endif

" == Abbrs == {{{1
source ~/.vim/abbr.vim

" == Highlight == {{{1
" hi! link SignColumn   LineNr
" hi! link ShowMarksHLl DiffAdd
" hi! link ShowMarksHLu DiffChange

" Modeline {{{1
" vim: ts=2 sw=2 sts=4 et foldenable foldmethod=marker foldcolumn=1
