" general configuration
source ~/.vim/config.vim

" plugins installation and configuration
source ~/.vim/plugins.vim

" custom mappings
source ~/.vim/mappings.vim

" custom autocmds
source ~/.vim/autocmd.vim

" custom abbrs
source ~/.vim/abbr.vim