[information]
 name = "nord"
 background = "dark"
 author = ''

[palette]
 fg = '#D8DEE9' # nord4
 bg = '#2E3440' # nord0

 red = '#BF616A'
 orange = '#D08770'
 yellow = '#EBCB8B'
 green = '#A3BE8C'
 magenta = '#B48EAD'

 cyan = '#88C0D0' # nord8
 blue = '#5E81AC' # nord10

 white = '#ECEFF4' # nord6
 gray = '#4C566A' # nord3

# format: foreground background style special blend
[highlights]
 Normal = 'fg bg'
 Underlined         = '- - u'
 SpecialKey     ='- cyan'
 # EndOfBuffer    ='link:NonText'
 TermCursor     ='- - r'
 TermCursorNC   ='- -'
 NonText        ='blue - b'
 Directory      ='cyan -'
 ErrorMsg       ='white red'
 IncSearch      ='- - r'
 Search         ='- yellow'
 CurSearch      ='- -'
 MoreMsg        ='green - b'
 ModeMsg        ='- - b'
 LineNr         ='yellow'
 # LineNrAbove    ='link:LineNr'
 # LineNrBelow    ='link:LineNr'
 CursorLineNr   ='yellow - b'
 # CursorLineSign ='link:SignColumn'
 # CursorLineFold ='link:FoldColumn'
 Question       ='green - b'
 StatusLine     ='- - br'
 StatusLineNC   ='- - r'
 # WinSeparator   ='link:VertSplit'
 # VertSplit      ='link:Normal'
 Title          ='magenta - b'
 Visual         ='- gray'
 VisualNC       ='- -'
 WarningMsg     ='- red'
 WildMenu       ='- yellow'
 # Folded         ='ctermfg=14 ctermbg=242 guifg=Cyan guibg=DarkGrey'
 # FoldColumn     ='ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey'
 # DiffAdd        ='ctermbg=4 guibg=DarkBlue'
 # DiffChange     ='ctermbg=5 guibg=DarkMagenta'
 # DiffDelete     ='ctermfg=12 ctermbg=6 gui=bold guifg=Blue guibg=DarkCyan'
 # DiffText       ='cterm=bold ctermbg=9 gui=bold guibg=Red'
 SignColumn     ='- -'
 Conceal        ='- -'
 SpellBad       ='- - u red'
 SpellCap       ='- - u blue'
 SpellRare      ='- - u magenta'
 SpellLocal     ='- - u cyan'
 Pmenu          ='- magenta'
 PmenuSel       ='- gray'
 # PmenuKind      ='link:Pmenu'
 # PmenuKindSel   ='link:PmenuSel'
 # PmenuExtra     ='link:Pmenu'
 # PmenuExtraSel  ='link:PmenuSel'
 PmenuSbar      ='- gray'
 PmenuThumb     ='- white'
 TabLine        ='- gray u'
 TabLineSel     ='- - b'
 TabLineFill    ='- - r'
 CursorColumn   ='- yellow'
 CursorLine     ='gray - u'
 ColorColumn    ='red -'
 # QuickFixLine   ='link:Search'
 # Whitespace     ='link:NonText'
 NormalNC       ='- -'
 # MsgSeparator   ='link:StatusLine'
 # NormalFloat    ='link:Pmenu'
 MsgArea        ='- - '
 # FloatBorder    ='link:WinSeparator'
 WinBar         ='- - b'
 # WinBarNC       ='link:WinBar'
 Cursor         ='bg fg'
 # FloatTitle     ='link:Title'
 lCursor        ='bg fg'
 Normal         ='- -'
 # Substitute     ='link:Search'
 FloatShadow    ='- - - - 80'
 FloatShadowThrough ='- - - - 100'
 Error          ='red - b'
 Todo           ='yellow - b'
 # String         ='link:Constant'
 Constant       ='white -'
 # Character      ='link:Constant'
 # Number         ='link:Constant'
 # Boolean        ='link:Constant'
 # Float          ='link:Number'
 # Function       ='link:Identifier'
 Identifier     ='white -'
 # Conditional    ='link:Statement'
 Statement      ='cyan -'
 # Repeat         ='link:Statement'
 # Label          ='link:Statement'
 # Operator       ='link:Statement'
 # Keyword        ='link:Statement'
 # Exception      ='link:Statement'
 # Include        ='link:PreProc'
 PreProc        ='blue - b'
 # Define         ='link:PreProc'
 # Macro          ='link:PreProc'
 # PreCondit      ='link:PreProc'
 # StorageClass   ='link:Type'
 Type           ='cyan - b'
 # Structure      ='link:Type'
 # Typedef        ='link:Type'
 # Tag            ='link:Special'
 Special        ='orange -'
 # SpecialChar    ='link:Special'
 # Delimiter      ='link:Special'
 # SpecialComment ='link:Special'
 # Debug          ='link:Special'
 Comment        ='gray -'
 MatchParen     ='- cyan'
 Ignore         ='bg -'


[diagnostic]
 DiagnosticDeprecated     = '- - s red'
 DiagnosticUnnecessary    = 'link:Comment'
 DiagnosticError          = 'red'
 DiagnosticWarn           = 'orange'
 DiagnosticInfo           = 'blue'
 DiagnosticHint           = 'gray'
 DiagnosticOk             = 'green'
 DiagnosticUnderlineError = '- - u red'
 DiagnosticUnderlineWarn  = '- - u orange'
 DiagnosticUnderlineInfo  = '- - u blue'
 DiagnosticUnderlineHint  = '- - u gray'
 DiagnosticUnderlineOk    = '- - u green'

[treesitter]
"@text"              = 'link:Normal'

[lsp]
"@lsp"              = 'link:Normal'
# LspInlayHint   xxx links to NonText
