local codicons = gh.lazy_require("core.config").icons.codicons

vim.g.symbols_outline = {
  highlight_hovered_item = false,
  show_guides = false,
  auto_preview = true,
  position = "left",
  relative_width = true,
  width = 25,
  auto_close = true,
  show_numbers = false,
  show_relative_numbers = false,
  show_symbol_details = true,
  preview_bg_highlight = "Pmenu",
  keymaps = {
    close = { "<Esc>", "q" },
    goto_location = "<Cr>",
    focus_location = "o",
    hover_symbol = "<C-space>",
    toggle_preview = "K",
    rename_symbol = "r",
    code_actions = "a",
  },
  lsp_blacklist = {},
  symbol_blacklist = {},
  symbols = {
    File = { icon = codicons.File, hl = "TSURI" },
    Module = { icon = codicons.Module, hl = "TSNamespace" },
    Namespace = { icon = codicons.Namespace, hl = "TSNamespace" },
    Package = { icon = codicons.Package, hl = "TSNamespace" },
    Class = { icon = codicons.Class, hl = "TSType" },
    Method = { icon = codicons.Method, hl = "TSMethod" },
    Property = { icon = codicons.Property, hl = "TSMethod" },
    Field = { icon = codicons.Field, hl = "TSField" },
    Constructor = {
      icon = codicons.Constructor,
      hl = "TSConstructor",
    },
    Enum = { icon = codicons.Enum, hl = "TSType" },
    Interface = { icon = codicons.Interface, hl = "TSType" },
    Function = { icon = codicons.Function, hl = "TSFunction" },
    Variable = { icon = codicons.Variable, hl = "TSConstant" },
    Constant = { icon = codicons.Constant, hl = "TSConstant" },
    String = { icon = codicons.String, hl = "TSString" },
    Number = { icon = codicons.Number, hl = "TSNumber" },
    Boolean = { icon = codicons.Boolean, hl = "TSBoolean" },
    Array = { icon = codicons.Array, hl = "TSConstant" },
    Object = { icon = codicons.Object, hl = "TSType" },
    Key = { icon = codicons.Key, hl = "TSType" },
    Null = { icon = codicons.Null, hl = "TSType" },
    EnumMember = { icon = codicons.EnumMember, hl = "TSField" },
    Struct = { icon = codicons.Struct, hl = "TSType" },
    Event = { icon = codicons.Event, hl = "TSType" },
    Operator = { icon = codicons.Operator, hl = "TSOperator" },
    TypeParameter = {
      icon = codicons.TypeParameter,
      hl = "TSParameter",
    },
  },
}

gh.map("n", "T", [[<cmd>SymbolsOutline<cr>]])
