local symbol_icons = as.lazy_require("core.config").symbol_icons

vim.g.symbols_outline = {
  highlight_hovered_item = false,
  show_guides = false,
  auto_preview = true,
  position = "left",
  relative_width = true,
  width = 25,
  auto_close = true,
  show_numbers = false,
  show_relative_numbers = false,
  show_symbol_details = true,
  preview_bg_highlight = "Pmenu",
  keymaps = {
    close = { "<Esc>", "q" },
    goto_location = "<Cr>",
    focus_location = "o",
    hover_symbol = "<C-space>",
    toggle_preview = "K",
    rename_symbol = "r",
    code_actions = "a",
  },
  lsp_blacklist = {},
  symbol_blacklist = {},
  symbols = {
    File = { icon = symbol_icons.File, hl = "TSURI" },
    Module = { icon = symbol_icons.Module, hl = "TSNamespace" },
    Namespace = { icon = symbol_icons.Namespace, hl = "TSNamespace" },
    Package = { icon = symbol_icons.Package, hl = "TSNamespace" },
    Class = { icon = symbol_icons.Class, hl = "TSType" },
    Method = { icon = symbol_icons.Method, hl = "TSMethod" },
    Property = { icon = symbol_icons.Property, hl = "TSMethod" },
    Field = { icon = symbol_icons.Field, hl = "TSField" },
    Constructor = {
      icon = symbol_icons.Constructor,
      hl = "TSConstructor",
    },
    Enum = { icon = symbol_icons.Enum, hl = "TSType" },
    Interface = { icon = symbol_icons.Interface, hl = "TSType" },
    Function = { icon = symbol_icons.Function, hl = "TSFunction" },
    Variable = { icon = symbol_icons.Variable, hl = "TSConstant" },
    Constant = { icon = symbol_icons.Constant, hl = "TSConstant" },
    String = { icon = symbol_icons.String, hl = "TSString" },
    Number = { icon = symbol_icons.Number, hl = "TSNumber" },
    Boolean = { icon = symbol_icons.Boolean, hl = "TSBoolean" },
    Array = { icon = symbol_icons.Array, hl = "TSConstant" },
    Object = { icon = symbol_icons.Object, hl = "TSType" },
    Key = { icon = symbol_icons.Key, hl = "TSType" },
    Null = { icon = symbol_icons.Null, hl = "TSType" },
    EnumMember = { icon = symbol_icons.EnumMember, hl = "TSField" },
    Struct = { icon = symbol_icons.Struct, hl = "TSType" },
    Event = { icon = symbol_icons.Event, hl = "TSType" },
    Operator = { icon = symbol_icons.Operator, hl = "TSOperator" },
    TypeParameter = {
      icon = symbol_icons.TypeParameter,
      hl = "TSParameter",
    },
  },
}

as.map("n", "T", [[<cmd>SymbolsOutline<cr>]])
