"$schema" = 'https://starship.rs/config-schema.json'

# https://starship.rs/config/#prompt
# Prompt {{{
# https://starship.rs/config/#default-prompt-format
format = """
$directory\
$character\
"""

# https://starship.rs/advanced-config/#enable-right-prompt
right_format = """
$git_branch\
$hostname\
"""

add_newline = false
scan_timeout = 10
# }}}

# left {{{
[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 9
truncation_symbol = '…/'

[character]
# success_symbol = "[➜](bold green)"
# error_symbol = "[✘](bold red) "
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"
# }}}

# right {{{
[git_branch]
disabled = true
format = " [$symbol$branch]($style) "

[hostname]
disabled = false
ssh_only = true
format = '[$hostname]($style) in '
# }}}

## vim: foldmethod=marker
