# https://starship.rs/config

# Prompt {{{
format = """
$directory\
$character\
"""

right_format = """
$git_branch\
$hostname\
"""

add_newline = false
# }}}

[username]
disabled = true

[hostname]
disabled = false
ssh_only = true
format = '[$hostname]($style) in '

[localip]
disabled = true

[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 8

[character]
# success_symbol = "[➜](bold green)"
# error_symbol = "[✘](bold red) "
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[line_break]
disabled = true

[package]
disabled = true

# [memory_usage]
# disabled = false
# threshold = -1
# symbol = " "
# style = "bold dimmed green"

# Git {{{1
[git_branch]
disabled = true
format = " [$symbol$branch]($style) "

[git_status]
disabled = true

[git_commit]
disabled = true
# }}}

# Languages {{{
[golang]
disabled = true

[lua]
disabled = true
# }}}


## vim: foldmethod=marker
