# Key Binding --------{{{
# don't suspend-client
unbind C-z

## Session
# Change prefix to Ctrl-f
unbind C-b
set -g prefix C-f
bind C-f send-prefix

# Use Enter instead of [ for copy mode
unbind [
# bind Enter copy-mode
# bind Escape copy-mode
bind v copy-mode
unbind p
bind p paste-buffer
bind -T copy-mode-vi v send-keys -X begin-selection
# bind -T copy-mode-vi y send-keys -X copy-selection
# linux clipboard
if-shell '[[ $(uname -s) = Linux ]]' {
    bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -i -sel clipboard'; 
    bind C-c run "tmux save-buffer - | xclip -i -sel clipboard"; 
    bind C-v run 'tmux set-buffer "$(xclip -o -sel clipboard)"; tmux paste-buffer'
}
# macos clipboard
# if-shell "uname | grep -q Darwin" {
#     bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'tmux save-buffer - | pbcopy'; \
#     bind C-c run 'tmux save-buffer - | pbcopy'; \
#     bind C-v run 'tmux set-buffer "$(pbpaste)"; tmux paste-buffer'
# }

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# kill Session
bind Q kill-session

## Window
# Create a new window
bind c new-window -c "#{pane_current_path}"

# Move window to left
bind -r \[ swap-window -t -1\; select-window -t -1
bind -r \] swap-window -t +1\; select-window -t +1

# kill window
bind X kill-window

# next or porvious window
bind C-n next-window
bind C-p previous-window

## Pane
# Fast pane spliting and switching 
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind \"
bind - split-window -v -c "#{pane_current_path}"

unbind q
bind p display-panes

bind -r h select-pane -L                   # h 等于向左移动光标
bind -r j select-pane -D                   # j 向下移动光标
bind -r k select-pane -U                   # k 向上移动光标
bind -r l select-pane -R                   # l 向右移动光标

# Resize-pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Kill Pane
bind x kill-pane

# Ctrl-f_n to toggle synchronize panes
bind n set-window-option synchronize-panes

# }}}


# Setting --------{{{

# set-option -g status-position top

## Session
#set mouse on
set -g mouse on

# Set history limit to something reasonable
set -g history-limit 102400

# Set vi-mode
setw -g mode-keys vi

# Index starts from 1
set-option -g base-index 1
set-option -g pane-base-index 1

# Renumber windows when a window is closed
set-option -g renumber-windows on

# Set terminal to 256 color
set -g default-terminal "screen-256color"

## status bar
set -g status-style fg=cyan,bg=black
# set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}\"#{=21:pane_title}\" %H:%M %y-%m-%d"
set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,} %H:%M %y-%m-%d"

## Window


# }}}


# Plugins --------{{{

# set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'junegunn/tmux-fzf-url'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# }}}
