#!/bin/sh
export EDITOR=vim
# go env
export GO111MODULE=on
#export GOPROXY=direct
export GOPROXY=https://goproxy.io
export GOSUMD=gosum.io+ce6e7565+AY5qEHUk/qmHc5btzW45JVoENfazw8LielDsaI+lEbq6
export GOPATH=~/env/golang/gopath
export GOBIN=$GOPATH/bin
export GOROOT=~/env/golang/go
# export PATH=$PATH:$GOBIN:$GOROOT/bin/

# docker
export DOCKER_DATA=~/env/docker/data
export DOCKER_CONF=~/env/docker/conf

# vagrant
export VGHOME=~/env/vm

# vagrant
export TMUXP=~/.tmuxp

path=(
    $HOME/bin
    $GOPATH/bin                              # golang
    $GOROOT/bin
    $HOME/.local/bin                         # pipx
    $path
  )
export PATH=":$PATH"
