#!/bin/sh
export DEV_ENV=$HOME/env
export DEV_TOOLS=$HOME/tools

if [ ! -d $DEV_ENV ]; then
    mkdir -p $DEV_ENV
fi

if [ ! -d $DEV_TOOLS ]; then
    mkdir -p $DEV_TOOLS
fi

# User configuration
for file in ~/.zsh.conf/*; do
    source $file
done

# starship
# export STARSHIP_CONFIG=$HOME/.config/zsh/config.toml
if [ ! -f "`which starship`" ]; then
	echo "Installing starship ..."
    sh -c "$(curl -fsSL https://starship.rs/install.sh)"
fi
eval "$(starship init zsh)"

# direnv
if [ ! -f "`which direnv`" ]; then
	echo "Installing direnv ..."
    sh -c "$(curl -fsSL https://direnv.net/install.sh)"
fi
eval "$(direnv hook zsh)"

# fzf
# if [ -f "`which fzf`" ]; then
#     [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# fi

# z.lua
# if type '_zlua' 2>/dev/null | grep -q 'function'; then
#     echo "Installing z.lua ..."
#     git clone https://github.com/skywind3000/z.lua.git $DEV_TOOLS/z.lua
# fi
[ -d $DEV_TOOLS/z.lua ] && eval "$(lua $DEV_TOOLS/z.lua/z.lua --init zsh)"

# https://unix.stackexchange.com/questions/332791/how-to-permanently-disable-ctrl-s-in-terminal
stty -ixon

# setxkbmap -option ctrl:swapcaps

# https://superuser.com/questions/523564/emacs-keybindings-in-zsh-not-working-ctrl-a-ctrl-e
bindkey -e