local M = {}

local palette = {
  pale_red = "#E06C75",
  dark_red = "#be5046",
  light_red = "#c43e1f",
  dark_orange = "#FF922B",
  green = "#98c379",
  bright_yellow = "#FAB005",
  light_yellow = "#e5c07b",
  dark_blue = "#4e88ff",
  magenta = "#c678dd",
  comment_grey = "#5c6370",
  grey = "#3E4556",
  whitesmoke = "#626262",
  bright_blue = "#51afef",
  teal = "#15AABF",
}

M.style = {
  border = {
    rectangle = { "┌", "─", "┐", "│", "┘", "─", "└", "│" },
    rounded = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  },
  icons = {
    lsp = {
      -- Error = "  ",
      -- WARN = "  ",
      -- INFO = "  ",
      -- HINT = "  ",
      Error = " ",
      Warn = " ",
      Info = " ",
      Hint = " ",
      CLIENT = "  ",
    },
    codicons = {
      Text = "",
      Method = "",
      Function = "",
      Constructor = "",
      Field = "ﰠ",
      Variable = "",
      Class = "ﴯ",
      Interface = "",
      Module = "",
      Property = "ﰠ",
      Unit = "塞",
      Value = "",
      Enum = "",
      Keyword = "",
      Snippet = "",
      Color = "",
      File = "",
      Reference = "",
      Folder = "",
      EnumMember = "",
      Constant = "",
      Struct = "פּ",
      Event = "",
      Operator = "",
      TypeParameter = "",
    },
    kinds = {
      Text = "",
      Method = "",
      Function = "",
      Constructor = "",
      Field = "", -- '',
      Variable = "", -- '',
      Class = "", -- '',
      Interface = "",
      Module = "",
      Property = "ﰠ",
      Unit = "塞",
      Value = "",
      Enum = "",
      Keyword = "", -- '',
      Snippet = "", -- '', '',
      Color = "",
      File = "",
      Reference = "", -- '',
      Folder = "",
      EnumMember = "",
      Constant = "", -- '',
      Struct = "", -- 'פּ',
      Event = "",
      Operator = "",
      TypeParameter = "",
    },
  },
  palette = palette,
}

return M.style
