local completion_item_kinds = {
	-- https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions
	-- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemKind
	Text = { icon = " ", hl = "@text" },
	Method = { icon = "󰆧 ", hl = "@method" },
	Function = { icon = "󰊕 ", hl = "@function" },
	Constructor = { icon = " ", hl = "@constructor" },
	Field = { icon = " ", hl = "@field" },
	Variable = { icon = "󰀫 ", hl = "@variable" },
	Class = { icon = " ", hl = "@type" },
	Interface = { icon = " ", hl = "@type" },
	Module = { icon = " ", hl = "@include" },
	Property = { icon = " ", hl = "@property" },
	Unit = { icon = " ", hl = "@text" },
	Value = { icon = "󰎠 ", hl = "@text" },
	Enum = { icon = " ", hl = "@type" },
	Keyword = { icon = " ", hl = "@keyword" },
	Snippet = { icon = " ", hl = "@text" },
	Color = { icon = "󰏘 ", hl = "@text" },
	File = { icon = "󰈙 ", hl = "@text" },
	Reference = { icon = " ", hl = "@text.reference" },
	Folder = { icon = " ", hl = "Directory" },
	EnumMember = { icon = " ", hl = "@constant" },
	Constant = { icon = " ", hl = "@constant" },
	Struct = { icon = " ", hl = "@type" },
	Event = { icon = " ", hl = "@text" },
	Operator = { icon = "󰆕 ", hl = "@operator" },
	TypeParameter = { icon = " ", hl = "@type" },
}

local symbol_kinds = {
	-- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#symbolKind
	File = completion_item_kinds.File,
	Module = completion_item_kinds.Module,
	Namespace = { icon = " ", hl = "Macro" },
	Package = { icon = " ", hl = "Macro" },
	Class = completion_item_kinds.Class,
	Method = completion_item_kinds.Method,
	Property = completion_item_kinds.Property,
	Field = completion_item_kinds.Field,
	Constructor = completion_item_kinds.Constructor,
	Enum = completion_item_kinds.Enum,
	Interface = completion_item_kinds.Interface,
	Function = completion_item_kinds.Function,
	Variable = completion_item_kinds.Variable,
	Constant = completion_item_kinds.Constant,
	String = completion_item_kinds.String,
	Number = completion_item_kinds.Number,
	Boolean = completion_item_kinds.Boolean,
	Array = { icon = "󰅪 ", hl = "Identifier" },
	Object = completion_item_kinds.Object,
	Key = completion_item_kinds.Key,
	Null = completion_item_kinds.Null,
	EnumMember = completion_item_kinds.EnumMember,
	Struct = completion_item_kinds.Struct,
	Event = completion_item_kinds.Event,
	Operator = completion_item_kinds.Operator,
	TypeParameter = completion_item_kinds.TypeParameter,
}

return {
	symbol_kinds = symbol_kinds,
	completion_item_kinds = completion_item_kinds,
	diagnostics = {
		-- ERROR = "E",
		-- WARN = "W",
		-- INFO = "I",
		-- HINT = "H",

		ERROR = "",
		WARN = "",
		INFO = "",
		HINT = "",

		-- ERROR = "Ⓔ",
		-- WARN = "Ⓦ",
		-- INFO = "Ⓘ",
		-- HINT = "Ⓗ",
	},
	arrows = {
		right = "",
		left = "",
		up = "",
		down = "",
	},
	fold = { "", "" },
	directory = " ",
	bug = "",
	git = "",
	bulb = "💡",
	search = "",
}
